apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: debugger
        command: ["bash"]
        args: ["-c", "while true; do sleep 10; done"]
        env:
        {{- include "network-debugger.envVars" . | nindent 8 }}
        image: "{{ .Values.global.dockerRepository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
      - name: docker
        env:
        image: "{{ .Values.global.dockerRepository }}/docker:{{ .Values.dockerImageTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      {{- if .Values.global.useImagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.appName }}-pull-secret
      {{- end }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
