apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      {{- if .Values.extraInitContainers }}
      {{ toYaml .Values.extraInitContainers | indent 6 }}
      {{- end }}
      containers:
      {{- if .Values.sideCars }}
      {{ toYaml .Values.sideCars | indent 6 }}
      {{- end }}
      - name: debugger
        command: ["bash"]
        args: ["-c", "while true; do sleep 10; done"]
        env:
        {{- include "network-debugger.envVars" . | nindent 8 }}
        image: "{{ .Values.global.dockerRepository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
      {{- if .Values.docker.enabled }}
      - name: docker
        command: ["sh"]
        args: ["-c", "while true; do sleep 10; done"]
        env:
        image: "{{ .Values.global.dockerRepository }}/{{ .Values.docker.image.name }}:{{ .Values.docker.image.tag }}"
        imagePullPolicy: {{ .Values.docker.image.pullPolicy }}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      {{- end }}
      dnsPolicy: ClusterFirst
      {{- if .Values.global.useImagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.appName }}-pull-secret
      {{- end }}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: docker-sock
